// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

import "@/styles/globals.css";
import "@/styles/app.scss";
import { ReactNode } from 'react';

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      {children}
    </html>
  );
}
